# Generated by Django 2.2 on 2019-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190420_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordernumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickuptime',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
